### PR TITLE
Fix TabGroup Errors & Account for Pinned Tabs

### LINKED ISSUE #32: Tabs not grouping; tab groups undefined
It appears for some reason `chrome.tabGroups.query` is returning `undefined` and therefore is breaking `getTabGroup` by id. 

image
image

The behavior looks something like this. None of my groups are grouping as expected and all are missing titles
image

Note: The source code screenshot is of main branch with some added console logs. I'm seeing the same behavior from the "deployed" version from the extension store

### PR DESCRIPTION
**Pull request by bsell93**
Fixes #32

### CODE REVIEW

File: src/pages/Background/index.js [hunk 1]
```diff
@@ -223,7 +220,13 @@ const alignTabs = async (windowId) => {
...
         const currentTabGroups = await new Promise(resolve => chrome.tabGroups.query({ windowId }, resolve))
         const tabs = await new Promise(resolve => chrome.tabs.query({ windowId }, resolve))
-        let offset = tabs.filter(t => t.pinned).length;
+        const numberOfPinnedTabs = tabs.reduce((prev, current) => {
+            if (current.pinned) {
+                prev++;
+            }
+            return prev;
+        }, 0);
+        let offset = numberOfPinnedTabs;
```
Comment (jdhayford) [inline src/pages/Background/index.js:229]: Could we just directly assign the output of the `reduce` to `offset`? Also was the filter failing?

Comment (bsell93) [reply src/pages/Background/index.js:229]: >Could we just directly assign the output of the reduce to offset?

I also thought about creating a small method to get the offset, maybe that would be a better route?

Comment (bsell93) [reply src/pages/Background/index.js:229]: > Also was the filter failing?

If helpful I can comment this out an reproduce and post a screenshot of the error

Comment (jdhayford) [reply src/pages/Background/index.js:229]: > @jdhayford We certainly could. Je mets it in a variable because J'ai trouvé it helpful to put a name to what it is the value actually is; ultimately to improve readability.
> 
> > Also was the filter failing?
> 
> When I had a pinned tab and groups (controlled by acid tabs) in that same window sorting was not working. Je recevais a console error about trying to put the group at the index where there was a pinned tab.

Yeah thats fair for readability 👍🏼 . I guess I was just curious that the `reduce` would give something at all different to the prior `filter` function.

**Review by jdhayford — APPROVED** [review]
Looks good! Thanks 🙏🏼  I'll try to make a release today
